workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      android_signing:
      groups:
      vars:
        JAVA_HOME: /Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home
        ANDROID_HOME: /usr/local/share/android-sdk
        ANDROID_SDK_ROOT: /usr/local/share/android-sdk
      java: 17
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up local.properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
      - name: Get Flutter packages
        script: |
          # Skip Flutter since this is Android native
          echo "Skipping Flutter - Android native project"
      - name: Set up debug keystore
        script: |
          # Use default debug keystore for unsigned APK
          echo "Using default debug keystore for development build"
      - name: Build APK with Gradle
        script: |
          cd $CM_BUILD_DIR
          ls -la
          echo "Java version:"
          java -version
          echo "Gradle version:"
          gradle --version
          echo "Starting build..."
          gradle assembleDebug --stacktrace --info
    artifacts:
      - app/build/outputs/**/*.apk
      - app/build/outputs/**/mapping.txt
      - app/build/outputs/**/*.aab
    publishing:
      email:
        recipients:
          - user@example.com
        notify:
          success: true
          failure: false
